CLASS zcl_data_file_upload_alfa03 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_data_file_upload_alfa03 IMPLEMENTATION.
ENDCLASS.
